<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateGolfEventsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('golf_events', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('event_id');
            $table->date('date');
            $table->time('time');
            $table->text('location');
            $table->string('location_postal_code', 255);
            $table->text('agenda')->nullable();
            $table->text('rules')->nullable();
            $table->integer('player_price');
            $table->integer('team_price');

            $table->index('event_id', 'event_id');

            $table->foreign('event_id', 'golf_events_ibfk_1')->references('id')->on('events')->onDelete('CASCADE
')->onUpdate('RESTRICT');
            $table->timestamps();
            $table->softDeletes();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('golf_events');
    }
}
