<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAuctionItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('auction_items', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('auction_event_id')->unsigned();
            $table->string('title', 255);
            $table->text('description');
            $table->dateTime('start_date');
            $table->dateTime('end_date');
            $table->tinyInteger('reserve_price');
            $table->integer('minimum_bid_increment');
            $table->timestamps();
            $table->softDeletes();            
            $table->foreign('auction_event_id')
                    ->references('id')
                    ->on('auction_events')
                    ->onDelete('cascade');


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('auction_items');
    }
}
