<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAuctionItemsImagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('auction_items_images', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('auction_item_id');
            $table->string('image', 255);
            $table->foreign('auction_item_id', 'auction_items_images_ibfk_1')
                    ->references('id')
                    ->on('auction_items')
                    ->onDelete('CASCADE');
            $table->timestamps();
            $table->softDeletes();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('auction_items_images');
    }
}
