<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEventImagesTable extends Migration
{
    // /**
    //  * Run the migrations.
    //  *
    //  * @return void
    //  */
    // public function up()
    // {
    //     Schema::create('event_images', function (Blueprint $table) {
    //         $table->increments('id');
    //         $table->unsignedInteger('event_id');
    //         $table->string('image', 255);

    //         $table->index('event_id', 'event_id');

    //         $table->foreign('event_id', 'event_images_ibfk_1')
    //             ->references('id')
    //             ->on('events')
    //             ->onDelete('CASCADE')
    //             ->onUpdate('CASCADE');

    //     });
    // }

    // /**
    //  * Reverse the migrations.
    //  *
    //  * @return void
    //  */
    // public function down()
    // {
    //     Schema::dropIfExists('event_images');
    // }
}
