<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAuctionEventsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('auction_events', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('event_id');
            $table->unsignedInteger('auction_item_id');
            $table->foreign('event_id', 'auction_events_ibfk_1')
                    ->references('id')
                    ->on('events')
                    ->onDelete('CASCADE')
                    ->onUpdate('RESTRICT');
            $table->foreign('auction_item_id', 'auction_events_ibfk_2')
                    ->references('id')
                    ->on('auction_items')
                    ->onDelete('CASCADE')
                    ->onUpdate('RESTRICT');           

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('auction_events');
    }
}
