<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAuctionHistoryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('auction_history', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('auction_item_id');
            $table->integer('bid_price');
            $table->integer('bidder_id')->unsigned();
            $table->foreign('auction_item_id', 'auction_history_ibfk_1')
                    ->references('id')
                    ->on('auction_items')
                    ->onDelete('CASCADE')
                    ->onUpdate('RESTRICT');    
            $table->foreign('bidder_id', 'auction_history_ibfk_2')
                    ->references('id')
                    ->on('users')
                    ->onDelete('CASCADE')
                    ->onUpdate('RESTRICT');    
            $table->timestamps();
            $table->softDeletes();
            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('auction_history');
    }
}
